services:
  nginx:
    build: ./nginx
    depends_on:
    - myapp
    - auth_server
    command: /bin/sh -c "sleep 5 && nginx -g 'daemon off;'"
    ports:
    - '80:80'
    - '443:443'
    volumes:
      - ./public:/public
  mongo:
    image: mongo:4.2.5
  myapp:
    build: .
    
    environment:
      WAIT_HOSTS: mongo:27017
      DOCKER_DB: true
    volumes:
      - ./public:/public
  auth_server:
    build: 
      context: .
      dockerfile: auth/Dockerfile
    environment:
      WAIT_HOSTS: mongo:27017 
      DOCKER_DB: true
      